Repository christopherpeters-git/web-bomberman, pull requests merged in 2020-11, with the labels that each got.

#71 Added Dockerfile
  Dockerfile
Labels: enhancement

#72 Fixed win tracking
  Bomb.go
  Bomberman.go
  DatabaseCommunication.go
  Game.go
  Map.go
  MapCreator.go
  Movement.go
  Server.go
  frontend/game.html
  images/maptest.png
  images/testMap.png
Labels: enhancement, fix, performance

#74 Sudden death update
  Bomb.go
  Bomberman.go
  Game.go
  Movement.go
  Server.go
  Websocket.go
Labels: enhancement, performance
